### ISSUE TITLE
Can't write to google drive data file, but can read.

### ISSUE THREAD

**Issue by cpmadsen** [cpmadsen/blackberrymapping.github.io#2]
When I try to add a new row to the dataset in the shiny app, then 'commit' to google drive, I get the following error:

_Writing layer `fileb78399a241c' to data source 
  `C:\Users\Chris\AppData\Local\Temp\RtmpA3NoAU\fileb78399a241c.geojson' using driver `GeoJSON'
Writing 2 features with 3 fields and geometry type Polygon.
Warning: Error in : Client error: (403) Forbidden
The user does not have sufficient permissions for this file.
* domain: global
* reason: insufficientFilePermissions
* message: The user does not have sufficient permissions for this
  file.
  [No stack trace available]_

Is the data file on the google drive not open for me to add to?

**Comment by saeeshm** [comment]
Just needed to have an access token on your workstation.
